# Connect to MySQL
   # mysql -u root -p1234
# Create User and Grant Privileges
   # use mysql
   # select host, user from user
   # create user doge@'%' identified by '1234';
   # GRANT ALL PRIVILEGES ON chaterview.* TO 'doge'@'%' WITH GRANT OPTION;
   # FLUSH PRIVILEGES;
version: '3.9'
services:
  rds:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes: # Mount - container:/docker-entrypoint-initdb.d
      - ./local-rds-init.sql:/docker-entrypoint-initdb.d/local-rds-init.sql
    environment:
      MYSQL_DATABASE: chaterview
      MYSQL_USER: doge
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      TZ: UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci